consumer_count = 1

[mongo]
connection_string = "mongodb://koerberm:ieThe6qu@localhost:27017/?w=majority&appName=MetadataLoader"
database = "nfdi-test"
collection = "core-storage-meta-test"

[notifications]
endpoint = "https://api.scienceobjectsdb.nfdi-dev.gi.denbi.de"
api_token = "iyOeXsMAblp8C5VuohOtqeP+iZwBt1ATntXdd+xCs2teenSLBryHkvpNOUQy"
project_id = "7d5337a4-fdbe-49b0-b779-432451c79e53"
group = "CREATE"

[grpc]
bind_address = "0.0.0.0:4711"

[log]
level = "debug"